package core.service.error


enum class OperationsErrorCode {
    INCORRECT_USER_ID,
    INCORRECT_FUND_ID,
    INCORRECT_TRANSACTION_ID,

    INVALID_LOGIN,
    INVALID_USER_NAME,
    DUPLICATE_LOGIN,

    FUND_DESCRIPTION_TOO_LONG,
    FUND_NAME_TOO_LONG,

    TRANSACTION_DESCRIPTION_TOO_LONG,
    TRANSACTION_BALANCES_DELTAS_SUM_IS_NOT_ZERO
}